# docker-compose.yml
version: "3.8"
services:
  bot:
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - mongo
      - redis
    command: ["python", "bot.py"]

  webhook:
    build: .
    env_file: .env
    command: ["uvicorn", "webhook.server:app", "--host", "0.0.0.0", "--port", "8080"]
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data:
