# .github/workflows/python-ci.yml
name: Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install flake8 black pytest

      - name: Run flake8 (Lint)
        run: |
          flake8 admin_panel/ --statistics --count

      - name: Check formatting with Black
        run: |
          black --check .

      - name: Run unit tests
        run: |
          pytest -v --tb=short
